version: '3.8'
services:
  patreon_email_dl:
    image: gtt1229/patreon-email-dl
    container_name: patreon_email_dl
    environment:
      IMAP_SERVER: imap.gmail.com
      SUBJECT_KEYWORDS: ${SUBJECT_KEYWORDS}
      CRON_SCHEDULE: ${CRON_SCHEDULE}
      AUTO_MAKE_FOLDERS: ${AUTO_MAKE_FOLDERS}
      FIREFOX_CONTAINER_COOKIES: "true"
    volumes:
      - ./state:/app/state
      - ./logs:/app/logs
      - ./cookies.txt:/app/cookies.txt
      - ./firefox_config:/app/cookies
      - ./${OUTPUT_FOLDER}:/downloads
    secrets:
      - patreon_email_dl_secrets

  firefox_patreon_email_dl:
    image: jlesage/firefox
    container_name: firefox_patreon_email_dl
    ports:
      - "5801:5800"  # Access at http://localhost:5801
    volumes:
      - ./firefox_config:/config
    environment:
      - TZ=America/New_York
    #restart: unless-stopped

secrets:
  patreon_email_dl_secrets:
    file: ./patreon_email_dl.secret